# Generated by Django 4.1.1 on 2022-09-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedores', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
    ]
