# Generated by Django 4.1.1 on 2022-09-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_bodega_cliente_compra_embalaje_empleado_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ocurrencia', models.DateTimeField()),
                ('tipo_transaccion', models.CharField(max_length=10)),
                ('detalle', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='embalaje',
            name='precio_compra',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='embalaje',
            name='precio_venta',
            field=models.FloatField(),
        ),
    ]
